
# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 2000
    min-spare-threads: 30
  #tomcat启动的端口
  port: 8081

  servlet:
    #tomcat访问路径，类似tomcat/webapps下的项目名称
    context-path: /appserver
logging:
  level:
    com.example.test.mapper: debug


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML5
    cache: false
    enabled: true
    encoding: utf-8
    prefix: classpath:templates/
#    suffix: .html


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.entity

